### PR TITLE
Example of using Unmock in browser via `parcel`

### PR DESCRIPTION
**Pull request by ksaaskil**
- Add an example of using Unmock in browser
- Does not contain any tests yet, not sure yet what would be the best way to do that
- Uses hard-coded JSON data as the response returned by unmock as one cannot add services from a schema :(

### CODE REVIEW

**Comment by mikesol** [comment]
Just a comment, but could we test this out with cypress.io?

**Comment by ksaaskil** [comment]
Maybe, there's a TODO note in the README to add browser tests.

**Comment by mikesol** [comment]
When you write "one cannot add services from a schema", do you mean that the `unmock.nock` and the OpenAPI bridges do not work for/from the browser?

**Comment by ksaaskil** [comment]
`unmock.nock` works but one cannot define a service from OpenAPI schema.

Side comment: I think we should reconsider the name `unmock.nock`, I think it's quite confusing: if you just want to add a service mock, one could expect that `unmock.mock` would work.

**Comment by ksaaskil** [comment]
To have OpenAPI schemas work, there should be an API of the kind of `unmock.add(Service.fromOpenApi(mySchema))`.

**Comment by ksaaskil** [comment]
Added an issue for the new API if we want to do that. I think it would be a useful refactoring anyway, add the service loader reading services from `__unmock__` could simply use that  https://github.com/unmock/unmock-js/issues/367

**Pull request merged**
