### PR TITLE
Move Slack example to slack-typescript, add tsconfig.json.

### PR DESCRIPTION
**Pull request by ksaaskil**
- Move the Slack TypeScript example to `slack-typescript` folder so we can create other examples as well
- Add `tsconfig.json` to the example, I could not make it run successfully without specifying the compiler options and also disabling `noImplicitAny`

### CODE REVIEW

**Comment by ksaaskil** [comment]
So should there be another level of nesting then? If I want to add new TypeScript examples, I find it quite troublesome if they need to be added to an existing project as they should be minimal examples?

**Comment by idantene** [comment]
I'm not sure if we should put all examples together - just a thought, that probably we'd like to show interaction with multiple services. And if so, do we want copies of these services in several folders?

If we do decide to include all typescript examples in a single folder, we could add another level of nesting. It depends of course on how verbose and/or minimal we'd like to be. Would `typescript-examples/slack.test.ts` not suffice for Slack-specific tests? Or `typescript-examples/slack.basic.test.ts`, etc?

**Comment by ksaaskil** [comment]
> I'm not sure if we should put all examples together - just a thought, that probably we'd like to show interaction with multiple services. And if so, do we want copies of these services in several folders?

Yes, every folder should be a self-contained example.

> If we do decide to include all typescript examples in a single folder, we could add another level of nesting. It depends of course on how verbose and/or minimal we'd like to be. Would `typescript-examples/slack.test.ts` not suffice for Slack-specific tests? Or `typescript-examples/slack.basic.test.ts`, etc?

I think every example should have a given purpose and be independent of others, the name `slack-typescript` is not very good as it does not say what the example is for. I find it quite confusing to have multiple `*.test.ts` files in the same example.

**Comment by ksaaskil** [comment]
Next.js has very nicely organized examples [here](https://github.com/zeit/next.js/tree/canary/examples).

**Comment by idantene** [comment]
Fair enough. Maybe some of the specifications (copies) could be just links then? So that the pulling this repo would remain relatively small in size, and a change to a specification would affect all examples (read: specifications are sync'd across examples).

**Comment by ksaaskil** [comment]
Yep, we can think about once some of the specs are shared.

**Pull request merged**
